package com.sample;
/*
 * This Java source file was generated by the Gradle 'init' task. test
 */
public class MyCalculator {

	
	
	public int add (int firstNum, int secNum){
		System.out.println("test2");
		return firstNum + secNum ;
	}
	
		
	public boolean someTestMethod() {
        return true;
    }
}
